# Generated by Django 4.0.6 on 2022-07-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('父亲', '父亲'), ('母亲', '母亲'), ('姐姐', '姐姐'), ('妹妹', '妹妹'), ('哥哥', '哥哥'), ('弟弟', '弟弟')], help_text='关系', max_length=10, verbose_name='关系')),
                ('name', models.CharField(help_text='姓名', max_length=10, verbose_name='姓名')),
                ('mobile', models.CharField(blank=True, default='', help_text='电话', max_length=20, verbose_name='电话')),
            ],
        ),
        migrations.CreateModel(
            name='PersonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='姓名', max_length=10, verbose_name='姓名')),
                ('sex', models.BooleanField(choices=[(1, '男'), (0, '女')], help_text='性别', verbose_name='性别')),
                ('age', models.IntegerField(blank=True, help_text='年龄', null=True, verbose_name='年龄')),
                ('email', models.EmailField(blank=True, help_text='邮箱', max_length=254, verbose_name='邮箱')),
                ('phone', models.CharField(help_text='电话', max_length=11, unique=True, verbose_name='电话')),
                ('description', models.TextField(help_text='人气其他详细信息', verbose_name='人员其他详细信息')),
                ('icon', models.ImageField(blank=True, default='', help_text='头像', upload_to='head/', verbose_name='头像')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '人员信息表',
                'verbose_name_plural': '人员信息表',
                'ordering': ('create_time', '-age'),
            },
        ),
    ]
