# Generated by Django 4.0.6 on 2022-07-18 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='personmodel',
            name='owner',
            field=models.ForeignKey(help_text='创建人', on_delete=django.db.models.deletion.CASCADE, related_name='persons', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='familymodel',
            name='person',
            field=models.ForeignKey(help_text='所属人', on_delete=django.db.models.deletion.CASCADE, related_name='families', to='persons.personmodel'),
        ),
    ]
