# Generated by Django 4.0.6 on 2022-07-18 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familymodel',
            options={'verbose_name': '家庭成员', 'verbose_name_plural': '家庭成员'},
        ),
        migrations.AddField(
            model_name='familymodel',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False, help_text='创建时间', verbose_name='创建时间'),
        ),
    ]
