# Generated by Django 4.0.6 on 2022-07-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_alter_familymodel_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmodel',
            name='phone',
            field=models.CharField(help_text='电话', max_length=11, unique=True, verbose_name='电话'),
        ),
    ]
