# Generated by Django 4.0.6 on 2022-07-19 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familymodel',
            options={'ordering': ('-update_time',), 'verbose_name': '家庭成员', 'verbose_name_plural': '家庭成员'},
        ),
        migrations.AlterModelOptions(
            name='personmodel',
            options={'ordering': ('-update_time',), 'verbose_name': '人员信息表', 'verbose_name_plural': '人员信息表'},
        ),
    ]
