# Generated by Django 4.0.6 on 2022-07-17 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0003_alter_personmodel_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personmodel',
            old_name='mail',
            new_name='email',
        ),
    ]
