# Generated by Django 4.0.6 on 2022-07-20 01:41

from django.conf import settings
from django.db import migrations, models
import utils.app.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('persons', '0004_alter_familymodel_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymodel',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='personmodel',
            name='owner',
            field=models.ForeignKey(db_constraint=False, help_text='关联用户自动填充', on_delete=models.SET(utils.app.models.get_sentinel_user), to=settings.AUTH_USER_MODEL, verbose_name='关联用户'),
        ),
    ]
