# Generated by Django 4.0.6 on 2022-07-18 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcartmodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='orderinfomodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='ordergoodmodel',
            name='good',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='goods.goodmodel', verbose_name='商品'),
        ),
        migrations.AddField(
            model_name='ordergoodmodel',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='goods.orderinfomodel', verbose_name='订单信息'),
        ),
        migrations.AddField(
            model_name='goodmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goodcategorymodel', verbose_name='商品类目'),
        ),
        migrations.AddField(
            model_name='goodcategorymodel',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='goods.goodcategorymodel', verbose_name='父级类别'),
        ),
        migrations.AlterUniqueTogether(
            name='shoppingcartmodel',
            unique_together={('owner', 'good')},
        ),
    ]
