# Generated by Django 4.0.6 on 2022-07-19 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodcategorymodel',
            options={'ordering': ('-update_time',), 'verbose_name': '商品类别', 'verbose_name_plural': '商品类别'},
        ),
        migrations.AlterModelOptions(
            name='goodmodel',
            options={'ordering': ('-update_time',), 'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterModelOptions(
            name='ordergoodmodel',
            options={'ordering': ('-update_time',), 'verbose_name': '订单商品', 'verbose_name_plural': '订单商品'},
        ),
        migrations.AlterModelOptions(
            name='orderinfomodel',
            options={'ordering': ('-update_time',), 'verbose_name': '订单', 'verbose_name_plural': '订单'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcartmodel',
            options={'ordering': ('-update_time',), 'verbose_name': '购物车', 'verbose_name_plural': '购物车'},
        ),
    ]
