# Generated by Django 4.0.6 on 2022-07-18 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodcategorymodel',
            options={'ordering': ('-create_time',), 'verbose_name': '商品类别', 'verbose_name_plural': '商品类别'},
        ),
        migrations.AlterModelOptions(
            name='goodmodel',
            options={'ordering': ('-create_time',), 'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterModelOptions(
            name='ordergoodmodel',
            options={'ordering': ('-create_time',), 'verbose_name': '订单商品', 'verbose_name_plural': '订单商品'},
        ),
        migrations.AlterModelOptions(
            name='orderinfomodel',
            options={'ordering': ('-create_time',), 'verbose_name': '订单', 'verbose_name_plural': '订单'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcartmodel',
            options={'ordering': ('-create_time',), 'verbose_name': '购物车', 'verbose_name_plural': '购物车'},
        ),
        migrations.RenameField(
            model_name='ordergoodmodel',
            old_name='add_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='shoppingcartmodel',
            old_name='add_time',
            new_name='create_time',
        ),
    ]
