# Generated by Django 4.0.6 on 2022-07-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_goodcategorymodel_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodcategorymodel',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='goodmodel',
            old_name='desc',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='goodmodel',
            name='brief_desc',
            field=models.CharField(max_length=500, verbose_name='商品简短描述'),
        ),
        migrations.AlterField(
            model_name='goodmodel',
            name='images',
            field=models.CharField(max_length=1024, verbose_name='商品图片列表'),
        ),
    ]
