# Generated by Django 4.0.6 on 2022-07-20 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_alter_shoppingcartmodel_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodcategorymodel',
            name='category_type',
            field=models.IntegerField(choices=[(1, '一级类目'), (2, '二级类目'), (3, '三级类目')], default=1, help_text='类目级别', verbose_name='类目级别'),
        ),
        migrations.AlterField(
            model_name='goodcategorymodel',
            name='description',
            field=models.TextField(blank=True, default='', help_text='类别描述', verbose_name='类别描述'),
        ),
    ]
