# Generated by Django 4.0.6 on 2022-07-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smscodemodel',
            options={'ordering': ('-update_time',), 'verbose_name': '短信验证码', 'verbose_name_plural': '短信验证码'},
        ),
        migrations.AlterModelOptions(
            name='usermodel',
            options={'ordering': ('-update_time',), 'verbose_name': '用户信息表', 'verbose_name_plural': '用户信息表'},
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='nickname',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='name',
            field=models.CharField(default='', help_text='请输入您的姓名或昵称', max_length=50, verbose_name='姓名'),
        ),
    ]
