# Generated by Django 4.0.6 on 2022-07-12 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='image',
            new_name='icon',
        ),
    ]
