# Generated by Django 4.0.6 on 2022-07-18 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smscodemodel',
            options={'verbose_name': '短信验证码', 'verbose_name_plural': '短信验证码'},
        ),
        migrations.AddField(
            model_name='departmentmodel',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间'),
        ),
    ]
