# Generated by Django 4.0.6 on 2022-07-20 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_smscodemodel_options_alter_usermodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'ordering': ('-update_time',), 'verbose_name': '用户管理', 'verbose_name_plural': '用户管理'},
        ),
        migrations.AddField(
            model_name='usermodel',
            name='handover_id',
            field=models.IntegerField(default=0, verbose_name='数据交接人'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='mobile',
            field=models.CharField(default='', help_text='请输入11位的手机号', max_length=11, verbose_name='手机号'),
        ),
    ]
