# Generated by Django 4.0.6 on 2022-07-14 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_image_usermodel_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsCodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号')),
                ('code', models.CharField(max_length=4, verbose_name='验证码')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
        ),
    ]
