# Generated by Django 4.0.6 on 2022-07-20 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usermodel_options_usermodel_handover_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentmodel',
            options={'ordering': ('-update_time',), 'verbose_name': '部门管理', 'verbose_name_plural': '部门管理'},
        ),
    ]
