# Generated by Django 4.0.6 on 2022-07-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_smscodemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='mobile',
            field=models.CharField(default=12345678901, help_text='请输入11位的手机号', max_length=11, verbose_name='手机号'),
            preserve_default=False,
        ),
    ]
