# Generated by Django 4.0.6 on 2022-07-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usermodel_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smscodemodel',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
