# Generated by Django 4.0.6 on 2022-07-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_smscodemodel_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='smscodemodel',
            name='used',
            field=models.BooleanField(default=0, verbose_name='是否被使用'),
        ),
    ]
