# Generated by Django 4.0.6 on 2022-07-17 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_smscodemodel_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='nick_name',
            new_name='nickname',
        ),
    ]
