# Generated by Django 4.0.6 on 2022-07-18 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='articletagmodel',
            name='owner',
            field=models.ForeignKey(help_text='创建人', on_delete=django.db.models.deletion.CASCADE, related_name='article_tag', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, help_text='请选择一些标签', related_name='tags', to='articles.articletagmodel', verbose_name='标签'),
        ),
        migrations.AlterUniqueTogether(
            name='articletagmodel',
            unique_together={('owner', 'name')},
        ),
    ]
