# Generated by Django 4.0.6 on 2022-07-14 23:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articletagmodel',
            options={'ordering': ('create_time',), 'verbose_name': '文章标签表', 'verbose_name_plural': '文章标签表'},
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='content',
            field=models.TextField(verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, related_name='tags', to='articles.articletagmodel'),
        ),
        migrations.AlterUniqueTogether(
            name='articletagmodel',
            unique_together={('name', 'owner')},
        ),
    ]
