# Generated by Django 4.0.6 on 2022-07-19 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletagmodel',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='标签名称'),
        ),
        migrations.AlterField(
            model_name='articletagmodel',
            name='owner',
            field=models.ForeignKey(db_constraint=False, help_text='创建人自动填充', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
    ]
