# Generated by Django 4.0.6 on 2022-07-15 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_alter_articletagmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlemodel',
            options={'ordering': ('create_time',), 'verbose_name': '文章表', 'verbose_name_plural': '文章表'},
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='content',
            field=models.TextField(help_text='请输入文章内容', verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, help_text='请选择一些标签', related_name='tags', to='articles.articletagmodel', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='title',
            field=models.CharField(help_text='请输入文章标题', max_length=100, verbose_name='文章标题'),
        ),
    ]
