# Generated by Django 4.0.6 on 2022-07-20 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_articlemodel_owner_alter_articletagmodel_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='content',
            field=models.TextField(blank=True, default='', help_text='请输入文章内容', verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='articletagmodel',
            name='name',
            field=models.CharField(max_length=20, verbose_name='标签名称'),
        ),
    ]
